# Keys
title = "Sprint 3b config"

[input_data]
shapefile_dir_path = "../data/input/bd_carto/ZONE_VEGETATION/"
shapefile_name = "ZONE_VEGETATION.shp"

ascii_file_dir_path = "../data/input/bd_alti/"
ascii_file_name = "BDALTIV2_25M_FXX_0875_6550_MNT_LAMB93_IGN69.asc"

[doc_data]
input_data_dir_path = "../doc/img/input_data/"
polygons_projection_dir_path = "../doc/img/polygons_projection/"
isochrones_dir_path = "../doc/img/isochrones/isochrones_for_making_gif/"

[fields_table]
default_field = "grass"

[nominal_speeds]
  [nominal_speeds.walk]
    reference = 100 # m/min
    wood = 0.30 # 30%
    sand = 0.60 # 60%
    grass = 1 # 100%
    road = 1 # 100%
    building = 0 # 0%
    water = 0 # 0%
    snow = 0.80 # 80%
    [[nominal_speeds.walk.angle]]
      range = [15, 90]
      coef = 0
    [[nominal_speeds.walk.angle]]
      range = [10, 15]
      coef = 0.20
    [[nominal_speeds.walk.angle]]
      range = [5, 10]
      coef = 0.60
    [[nominal_speeds.walk.angle]]
      range = [0, 5]
      coef = 1
    [[nominal_speeds.walk.angle]]
      range = [-5, 0]
      coef = 1.10
    [[nominal_speeds.walk.angle]]
      range = [-15, -5]
      coef = 1.30
    [[nominal_speeds.walk.angle]]
      range = [-90, -15]
      coef = 0

[[isochrones]]
id = 1
time = 50

[[isochrones]]
id = 2
time = 500

[[isochrones]]
id = 3
time = 1000
