# Keys
title = "Sprint 3b config"

["input_data"]
shapefile_dir_path = "/home/william/Programming/WazeTT/data/input/bd_topo/ZONE_VEGETATION/"
shapefile_name = "ZONE_VEGETATION.shp"

ascii_file_dir_path = "../data/input/bd_alti/"
ascii_file_name = "BDALTIV2_25M_FXX_0825_6550_MNT_LAMB93_IGN69.asc"

[nominal_speeds]
  [nominal_speeds.walk]
    reference = 6 # km/h
    bush = 30 # %
    sand = 60 # %
    road = 100 # %
    building = 0 # %
    water = 0 # %
    snow = 80 # %
    [[nominal_speeds.walk.angle]]
      range = [15, 90]
      coef = 0
    [[nominal_speeds.walk.angle]]
      range = [10, 15]
      coef = 20
    [[nominal_speeds.walk.angle]]
      range = [5, 10]
      coef = 60
    [[nominal_speeds.walk.angle]]
      range = [0, 5]
      coef = 100
    [[nominal_speeds.walk.angle]]
      range = [0, -5]
      coef = 110
    [[nominal_speeds.walk.angle]]
      range = [-5, -15]
      coef = 130
    [[nominal_speeds.walk.angle]]
      range = [-15, -90]
      coef = 0

[["isochrones"]]
id = 1
time = 5

[["isochrones"]]
id = 2
time = 10

[["isochrones"]]
id = 3
time = 30
